all:demo.cpp
	g++ -fpermissive demo.cpp  -o main -I../include  -L../lib -lDDSpeechLinuxSDK  -I../include/utilcxx -I../include/vad   -L../lib  -lcurlreq    -ljson_libmt  -lutilcxx  -lpthread  -lglog  -lcurl  -lvadbv  -lz
