all:demo.cpp
	g++ -fpermissive demo2.cpp  -o main2 -I../include  -L../lib -lDDSpeechLinuxSDK  -I../include/utilcxx -I../include/vad   -L../lib  -lcurlreq    -ljson_libmt  -lutilcxx  -lpthread  -lglog  -lcurl  -lvadbv  -lz
	g++ -fpermissive demo.cpp  -o main1 -I../include  -L../lib -lDDSpeechLinuxSDK  -I../include/utilcxx -I../include/vad   -L../lib  -lcurlreq    -ljson_libmt  -lutilcxx  -lpthread  -lglog  -lcurl  -lvadbv  -lz
